name: PyLint

on:
  push:
    branches:
      - "**"
    paths:
      - "backend/**"
      - ".github/workflows/pylint.yml"
  pull_request:
    branches:
      - "master"
    paths:
      - "backend/**"
      - ".github/workflows/pylint.yml"

permissions:
  contents: write
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install neccessary packages
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: Sort imports with Ruff
        run: |
          ruff check . --select I --fix
      - name: Format with Ruff
        run: |
          ruff format .
      - name: Commit autofixes
        run: |
          git commit -am "Apply Ruff formatting" || echo No Ruff changes to commit!
          git push
